import{a as S,S as P,i}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const E="52841982-f1748b7cc828c4a83b5032abb",v="https://pixabay.com/api/";async function p(e,r=1){const o=new URLSearchParams({key:E,q:e,image_type:"photo",safesearch:!0,page:r,per_page:15});try{return(await S.get(`${v}?${o}`)).data}catch(a){throw console.error("Error fetching images from Pixabay:",a),new Error("Failed to fetch images from Pixabay.")}}const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),d=document.querySelector(".load-more-btn"),q=new P(".gallery a",{captionsData:"alt",captionDelay:250});function $(e){const r=e.tags.split(",").map(o=>o.trim()).slice(0,3).join(", ");return`
  <li class="gallery-item">
    <a class="gallery-link" href="${e.largeImageURL}" >  
        <img
            class="gallery-image"
            src="${e.webformatURL}"
            alt="${r}"
            width="360"
            />
        <div class="info">
            <p class="info-item"><b>Likes</b> ${e.likes}</p>
            <p class="info-item"><b>Views</b> ${e.views}</p>
            <p class="info-item"><b>Comments</b> ${e.comments}</p>
            <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
    </a>
    </li>`}function b(e){if(!l){console.error("Gallery container not found in DOM!");return}const r=e.map($).join("");l.insertAdjacentHTML("beforeend",r),q.refresh()}function M(){l&&(l.innerHTML="")}function L(){u&&u.classList.remove("is-hidden")}function c(){u&&u.classList.add("is-hidden")}function h(){d&&d.classList.remove("is-hidden")}function f(){d&&d.classList.add("is-hidden")}const w=document.querySelector(".form"),R=document.querySelector(".load-more-btn"),B=document.querySelector(".gallery");let y="",n=1,g=0;const C=15;w.addEventListener("submit",k);R.addEventListener("click",x);async function k(e){e.preventDefault();const r=e.currentTarget.elements["search-text"].value.toLowerCase().trim();if(r===""){i.error({title:"Error",message:"Enter a search term",position:"topRight"});return}y=r,n=1,M(),f(),L();try{const o=await p(y,n);if(c(),o.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g=Math.ceil(o.totalHits/C),b(o.hits),i.success({title:"Success",message:`We found ${o.totalHits} images.`,position:"topRight"}),n<g?h():(f(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",timeout:5e3}))}catch(o){c(),i.error({title:"Error",message:"Failed to fetch images. Please check your network connection.",position:"topRight"}),console.error("Error:",o.message)}finally{c(),w.reset()}}async function x(){n+=1,f(),L();try{const e=await p(y,n);b(e.hits),O(),n<g?h():(f(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",timeout:5e3}))}catch(e){i.error({title:"Error",message:"Failed to fetch images. Please check your network connection.",position:"topRight"}),console.error("Error:",e.message),h()}finally{c()}}function O(){const e=B.querySelector(".gallery-item");if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
