import{a as S,S as P,i}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&n(m)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const E="52841982-f1748b7cc828c4a83b5032abb",v="https://pixabay.com/api/";async function y(e,t=1){const o=new URLSearchParams({key:E,q:e,image_type:"photo",safesearch:!0,page:t,per_page:15});try{return(await S.get(`${v}?${o}`)).data}catch(n){throw console.error("Error fetching images from Pixabay:",n),new Error("Failed to fetch images from Pixabay.")}}const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),d=document.querySelector(".load-more-btn"),R=new P(".gallery a",{captionData:"alt",captionDelay:250});function $(e){const t=e.tags.split(",").map(o=>o.trim()).slice(0,3).join(", ");return`
  <li class="gallery-item">
    <a class="gallery-link" href="${e.largeImageURL}"  data-alt="${t}">  
        <img
            class="gallery-image"
            src="${e.webformatURL}"
            alt="${t}"
            width="360"
            />
        <div class="info">
            <p class="info-item"><b>Likes</b> ${e.likes}</p>
            <p class="info-item"><b>Views</b> ${e.views}</p>
            <p class="info-item"><b>Comments</b> ${e.comments}</p>
            <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
    </a>
    </li>`}function b(e){if(!l){console.error("Gallery container not found in DOM!");return}const t=e.map($).join("");l.insertAdjacentHTML("beforeend",t),R.refresh()}function q(){l&&(l.innerHTML="")}function L(){u&&u.classList.remove("is-hidden")}function c(){u&&u.classList.add("is-hidden")}function h(){d&&d.classList.remove("is-hidden")}function f(){d&&d.classList.add("is-hidden")}const w=document.querySelector(".form"),M=document.querySelector(".load-more-btn"),B=document.querySelector(".gallery");let g="",a=1,p=0;const k=15;w.addEventListener("submit",x);M.addEventListener("click",O);async function x(e){e.preventDefault();const t=e.currentTarget.elements["search-text"].value.toLowerCase().trim();if(t===""){i.error({title:"Error",message:"Enter a search term",position:"topRight"});return}g=t,a=1,q(),f(),L();try{const o=await y(g,a);if(c(),o.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=Math.ceil(o.totalHits/k),b(o.hits),i.success({title:"Success",message:`We found ${o.totalHits} images.`,position:"topRight"}),a<p?h():(f(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3}))}catch(o){c(),i.error({title:"Error",message:"Failed to fetch images. Please check your network connection.",position:"topRight"}),console.error("Error:",o.message)}finally{c(),w.reset()}}async function O(){a+=1,f(),L();try{const e=await y(g,a);b(e.hits),C(),a<p?h():(f(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3}))}catch(e){i.error({title:"Error",message:"Failed to fetch images. Please check your network connection.",position:"topRight"}),console.error("Error:",e.message),h()}finally{c()}}function C(){const e=B.querySelector(".gallery-item");if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
